name: Deploy to Hetzner Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          # Navigate to project directory
          cd /home/farsi-dutch-bot
          
          # Pull latest changes
          git pull origin master || echo "Git pull failed, continuing with rsync"
          
          # Install/update dependencies
          npm install
          
          # Restart bot with PM2
          pm2 restart farsi-dutch-bot || pm2 start ecosystem.config.js
          
          # Show status
          pm2 status
          
          echo "🚀 Deployment completed successfully!"
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi